### ISSUE TITLE
Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: 

### ISSUE THREAD

**Issue by bmwertman** [sarriaroman/FabricPlugin#127]
I am getting the below error when trying to build my cordova/ionic app for android. No issue with iOS build.   

    ERROR [2018-03-14 12:44:35.77]: Shell command exited with exit status 1 instead of 0.
    WARN [2018-03-14 12:44:35.77]: Lane Context:
    INFO [2018-03-14 12:44:35.77]: {:PLATFORM_NAME=>:android, :LANE_NAME=>"android beta", :GIT_REPO_WAS_CLEAN_ON_START=>true} 
    ERROR [2018-03-14 12:44:35.77]:  WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/Brad/Documents/apparent/platforms/android/build/outputs/apk/android-debug.apk
    Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	    at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	    at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
    Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/Brad/Documents/apparent/platforms/android/build/outputs/apk/android-debug.apk
	    at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	    ... 2 more

    INFO [2018-03-14 12:44:35.77]: Successfully generated documentation at path '/Users/Brad/Documents/apparent/fastlane/README.md'

    +------+-------------------------+-------------+
    |               fastlane summary               |
    +------+-------------------------+-------------+
    | Step | Action                  | Time (in s) |
    +------+-------------------------+-------------+
    | 1    | update_fastlane         | 2           |
    | 2    | ensure_git_status_clean | 0           |
    | 3    | patch                   | 0           |
    | 4    | cordova                 | 8           |
    | 💥   | crashlytics             | 2           |
    +------+-------------------------+-------------+

    DEBUG [2018-03-14 12:44:35.78]: All plugins are up to date
    ERROR [2018-03-14 12:44:35.78]: fastlane finished with errors
    DEBUG [2018-03-14 12:44:35.78]: All plugins are up to date
    bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
    FastlaneCore::Interface::FastlaneError: [!]  WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/Brad/Documents/apparent/platforms/android/build/outputs/apk/android-debug.apk
    Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	    at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	    at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
    Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/Brad/Documents/apparent/platforms/android/build/outputs/apk/android-debug.apk
	    at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	    ... 2 more

**Comment by tsengvn** [comment]
i got the same error 

`Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/hienngo/Workspace/Android/taus-reel-android/app/build/outputs/apk/sit/debug/app-sit-debug.apk (FastlaneCore::Interface::FastlaneError)
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/hienngo/Workspace/Android/taus-reel-android/app/build/outputs/apk/sit/debug/app-sit-debug.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `call'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:34:in `block in parsing_binding'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/hienngo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
	from /Users/hienngo/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/hienngo/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'`

**Comment by hromyk** [comment]
The same.

**Comment by Karthik2007** [comment]
Same here. Any help?

**Comment by rusmichal** [comment]
bump

**Comment by Karthik2007** [comment]
It worked when I tried building release apk instead of debug apk. Don't know why it is giving error on debug build.

**Comment by gonzalonm** [comment]
Same error here using Flutter. I think you need Crashlytics plugin for each platform according to https://github.com/fastlane/fastlane/issues/9355#issuecomment-305999448
