### ISSUE TITLE
Runtime Exception: com.sarriaroman.fabric.FabricPlugin$1.run(FabricPlugin.java:118)

### ISSUE THREAD

**Issue by KentSpadzinski** [sarriaroman/FabricPlugin#23]
This exception has been reported already but the issue was closed ...  I am still experiencing the same problem   After installing the plugin, Fabric is initialized and working (app shows up in the fabric dashboard).  I am also receiving crash alerts.  However, as soon as I try to run the following test code:

window.fabric.Crashlytics.addLog("about to send a crash for testing!");
window.fabric.Crashlytics.sendCrash();

App closes and I get this reported back:

 Fatal Exception: java.lang.RuntimeException: This is a crash
       at com.sarriaroman.fabric.FabricPlugin$1.run(FabricPlugin.java:118)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6897)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by Justin-Credible** [comment]
That is correct behavior; the purpose of the `sendCrash()` method is to cause a native crash to occur so that you can verify that your crash reports are sent to Crashlytics.

**Comment by KentSpadzinski** [comment]
ok, that makes total sense now...  not sure why I didn't clue into that before!  Thanks for the quick reply.
