### ISSUE TITLE
Initialisation failed + crash

### ISSUE THREAD

**Issue by GuillaumeNachury** [sarriaroman/FabricPlugin#3]
Hi,
I'm trying to add the plugin to my project, but I'm facing several issues.
I don't really understand the plugin/framework init process. From my understanding of the fabric system, when the app is launch for the first time is should register / present itself to the backend (and appear under my organisation)
But I can't get my app registered on fabric.io.
Shouldn't the plugin call 
```
Fabric.with()
```
at some point ?

Another problem I have is when I use 
```
window.fabric.Answers.sendLogIn()
```

the app crash
```
E/AndroidRuntime(15212): FATAL EXCEPTION: main
E/AndroidRuntime(15212): Process: com.xxx.yyy, PID: 15212
E/AndroidRuntime(15212): java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
E/AndroidRuntime(15212): 	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:265)
E/AndroidRuntime(15212): 	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:516)
E/AndroidRuntime(15212): 	at com.crashlytics.android.answers.Answers.getInstance(Answers.java:45)
E/AndroidRuntime(15212): 	at com.sarriaroman.fabric.FabricPlugin$2.run(FabricPlugin.java:79)
E/AndroidRuntime(15212): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(15212): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15212): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15212): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(15212): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15212): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15212): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(15212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by sarriaroman** [comment]
Can you tell me the version of the Fabric plugin are you using in your project? Maybe something changed in the latest plugin and I need to change the way the plugin is initialised.

**Comment by GuillaumeNachury** [comment]
Since I don't have Android Studio in my dev env., I followed the manual install process : 
https://docs.fabric.io/android/fabric/integration.html#manual-setup

My build.gradle
```
buildscript {
  repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:1.0.+'
    // The Fabric Gradle plugin uses an open ended version to react
    // quickly to Android tooling updates
    classpath 'io.fabric.tools:gradle:1.+'
  }
}

apply plugin: 'com.android.application'
//Put Fabric plugin after Android plugin
apply plugin: 'io.fabric'

repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
}

...

dependencies{
compile('com.crashlytics.sdk.android:crashlytics:2.5.2@aar') 
    {
      transitive = true;
    }
}
```
