### ISSUE TITLE
Getting an "Cannot read property 'FABRIC_API_KEY' of undefined" installing the plugin

### ISSUE THREAD

**Issue by dazwin** [sarriaroman/FabricPlugin#31]
Verified using a sample project and I'm running the following:

`cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=###### --variable FABRIC_API_SECRET=######`

cordova v6.1.1
nodejs v4.4.3

Here's the full stack trace:
```
Fetching plugin "cordova-fabric-plugin" via npm
Installing "cordova-fabric-plugin" for ios
Failed to install 'cordova-fabric-plugin':TypeError: Cannot read property 'FABRIC_API_KEY' of undefined
    at Object.module.exports.getPluginConfig (/Users/darrenw/Projects/cordova_sample/hello/plugins/cordova-fabric-plugin/hooks/lib/utilities.js:60:64)
    at Object.module.exports.addShellScriptBuildPhase (/Users/darrenw/Projects/cordova_sample/hello/plugins/cordova-fabric-plugin/hooks/lib/ios-helper.js:22:38)
    at module.exports (/Users/darrenw/Projects/cordova_sample/hello/plugins/cordova-fabric-plugin/hooks/after_plugin_install.js:22:19)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:167:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:145:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
Error: Cannot read property 'FABRIC_API_KEY' of undefined
```

**Comment by jlacroix12** [comment]
I'm having the same issue. It was working last night but as of the recent update I can no longer add ios as a platform

**Comment by Justin-Credible** [comment]
@sarriaroman The plugin ID used by the build looks. It needs to be updated there as well.

See `hooks/lib/utilities.js`:

````
    /**
     * The ID of the plugin; this should match the ID in plugin.xml.
     */
    getPluginId: function () {
        return "com.sarriaroman.fabric";
    },
````

**Comment by sarriaroman** [comment]
@Justin-Credible yes... I was checking that the push failed for that change. My bad... I will be updating it right now.

**Comment by sarriaroman** [comment]
Solve with version 1.0.7. Sorry :(
