### ISSUE TITLE
cordova-fabric-plugin':Error: ENOENT: no such file or directory, open 'config.xml

### ISSUE THREAD

**Issue by danilovdev** [sarriaroman/FabricPlugin#38]
I have an error when I try to add ios platform with this plugin.

$ cordova platfrom add ios --save
Error: Cordova does not know platfrom; try `cordova help` for a list of all the available commands.
MacBook-Pro-Vaceslav:fo_web aleksejdanilov$ cordova platform add ios --save
Adding ios project...
iOS project created with cordova-ios@4.1.1
Installing "co.medicast.plugins.MapLauncher" for ios
Installing "com.organizer.plugins.callcapability" for ios
Installing "com.organizer.plugins.callcenter" for ios
Installing "cordova-fabric-plugin" for ios
Parsing config.xml failed
Failed to install 'cordova-fabric-plugin':Error: ENOENT: no such file or directory, open 'config.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.module.exports.parseElementtreeSync (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/util/xml-helpers.js:118:27)
    at Object.ConfigParser (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:33:24)
    at getAppName (/Users/aleksejdanilov/documents/work/organizer/fo/fo_web/plugins/cordova-fabric-plugin/hooks/lib/utilities.js:17:18)
    at Object.module.exports.getXcodeProjectPath (/Users/aleksejdanilov/documents/work/organizer/fo/fo_web/plugins/cordova-fabric-plugin/hooks/lib/utilities.js:79:23)
    at module.exports (/Users/aleksejdanilov/documents/work/organizer/fo/fo_web/plugins/cordova-fabric-plugin/hooks/after_plugin_install.js:20:42)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:167:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:145:16)
Error: ENOENT: no such file or directory, open 'config.xml'

**Comment by Justin-Credible** [comment]
Can you provide exact steps to reproduce from a new project?

I tested with Cordova 6.0.0 and 6.1.1 and was not able to reproduce.

Keep in mind, for the current plugin to work properly, you'll want to add the plugin **after** you've added your platforms so that the build hooks can update the platform files properly.

Here are the steps I used to try and reproduce your problem:

````
 $ node --version
v4.2.2

 $ cordova --version
6.1.1

$ cordova create TestApp4
Creating a new cordova project.

$ cd TestApp4

$ cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=xxx --variable FABRIC_API_SECRET=xxx
Fetching plugin "cordova-fabric-plugin" via npm

 $ cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@4.1.1
Installing "cordova-fabric-plugin" for ios
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for ios

 $ cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.cordova.hellocordova
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-23
Android project created with cordova-android@5.1.1
Installing "cordova-fabric-plugin" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
 $ cordova prepare ios

 $ cordova prepare android
````

**Comment by zwallacedev** [comment]
Was this resolved?

**Comment by schmkr** [comment]
I ran into this issue this afternoon, where in a project setup the config.xml file is not located in the root of the project, but in the `www` folder of the project. According to this function:
https://github.com/apache/cordova-lib/blob/843f7cc34dc2ae6520d656b3ad78168230b949bc/src/cordova/util.js
that should be possible and it works fine for every other plugin installed.

**Comment by ilyavinogradov** [comment]
This started happening after I upgraded Cordova to 8.0.0, and Cordova-android to 7.0.0. The plugin version was 1.1.9. Upgrading it to 1.1.10 seems to fix the problem.

**Comment by TKlarissa** [comment]
greetings everyone. am a beginner. am working on ionic project and i have upload button that gives me an error on click. please help

`chooseFile(){
    this.fileChooser.open().then((url) => {
      alert(url);

      this.file.resolveLocalFilesystemUrl(url).then((newUrl) => {
        alert(JSON.stringify(newUrl));

        let dirPath = newUrl.nativeURL;
        let dirPathSegments = dirPath.split('/');
        dirPathSegments.pop();
        dirPath = dirPathSegments.join('/');

        this.file.readAsArrayBuffer(dirPath, newUrl.name).then(async (buffer) => {
          await this.upload(buffer, newUrl.name);
        })
      })
    })
  }
      //the upload part that direct the file to firebase
      //and determine the file format
    async upload(buffer, name){
      let blob = new Blob([buffer], {type: "file/pdf,docx"});

      let storage = firebase.storage();

      storage.ref('files/' + name).put(blob).then((d) => {
        alert("Done");
      }).catch((error) => {
        alert(JSON.stringify(error));
      })
  }`
