### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Volumes/<volumeName>/<projectName>/platforms/ios/._<projectName>/config.xml'

### ISSUE THREAD

**Issue by mudolab** [sarriaroman/FabricPlugin#49]
On Mac OS X
I have move my project folder to a second partition on the hard disk with fat32 format and this error is happening:
`
cp: copyFileSync: could not write to dest file (code=ENOENT):/Volumes/Data/w_jboss/bajale_app/platforms/ios/._Bajale/config.xml

Parsing /Volumes/Data/w_jboss/bajale_app/platforms/ios/._Bajale/config.xml failed
Error: ENOENT: no such file or directory, open '/Volumes/Data/w_jboss/bajale_app/platforms/ios/._Bajale/config.xml'

`
or this 
`
vms-Mac:bajale_app vmmac$ cordova build android
shell.js: internal error
Error: ENOENT: no such file or directory, lstat '/Volumes/Data/w_jboss/bajale_app/platforms/android/assets/www/assets/._.DS_Store'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at rmdirSyncRecursive (/Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/node_modules/shelljs/src/rm.js:20:23)
    at rmdirSyncRecursive (/Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/node_modules/shelljs/src/rm.js:23:7)
    at /Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/node_modules/shelljs/src/rm.js:159:7
    at Array.forEach (native)
    at Object._rm (/Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/node_modules/shelljs/src/rm.js:123:9)
    at Object.rm (/Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/node_modules/shelljs/src/common.js:186:23)
    at updateWwwFrom (/Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/lib/prepare.js:96:11)
    at Api.module.exports.prepare (/Volumes/Data/w_jboss/bajale_app/platforms/android/cordova/lib/prepare.js:38:19)

`

**Comment by ilyavinogradov** [comment]
This started happening after I upgraded Cordova to 8.0.0, and Cordova-android to 7.0.0. The plugin version was 1.1.9. Upgrading it to 1.1.10 seems to fix the problem.
