### ISSUE TITLE
Execution failed for task ':fabricGenerateResourcesArmv7Debug'.

### ISSUE THREAD

**Issue by ruifilipeasilva** [sarriaroman/FabricPlugin#65]
I'm trying to implement this plugin in one meteor based project. But when i try to run the app, I'm getting this error:

```
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed: /Users/ruifilipesilva/Desktop/stash/app/.meteor/local/cordova-build/platforms/android/cordova/run --device
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':fabricGenerateResourcesArmv7Debug'.
   > Crashlytics Developer Tools error.
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   Error code 1 for command: /Users/ruifilipesilva/Desktop/stash/app/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildDebug,-b,/Users/ruifilipesilva/Desktop/stash/app/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
   undefined
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

/Users/ruifilipesilva/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1
```

Can someone help me on this?

**Comment by ruifilipeasilva** [comment]
Already resolved the issue, I think that I had a problem setting the API_KEY and SECRET.
