### ISSUE TITLE
Resetting platforms fails to install fabric plugin

### ISSUE THREAD

**Issue by paishin** [sarriaroman/FabricPlugin#93]
While trying to reset my platforms, fabric plugin fails to install
I added the plugin using the correct credentials and used  --save
I can see that FABRIC_API_KEY, FABRIC_API_SECRET are set as variables in config.xml

I get the following error:
```
Installing "cordova-fabric-plugin" for android


Failed to install 'cordova-fabric-plugin':Error: Variable(s) missing: FABRIC_API_KEY, FABRIC_API_SECRET
    at C:\Users\Panicos\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:362:23
    at _fulfilled (C:\Users\Panicos\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Panicos\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Panicos\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Panicos\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:557:44
    at flush (C:\Users\Panicos\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Error: Variable(s) missing: FABRIC_API_KEY, FABRIC_API_SECRET
```

**Comment by lucianomlima** [comment]
Variables in config.xml but same error here

**Comment by kurtiev** [comment]
`cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=XXX --variable FABRIC_API_SECRET=xxx`

Might be this KEYs - http://prntscr.com/hekwls. 

https://fabric.io/kits/ios/crashlytics/install
Not?

**Comment by 814k31** [comment]
If you guys are still having issues
Try make sure the fabric api key and variables go all through the chain
I had issues when it was in my config.xml and package.json however needed to also be in plugins/fetch.json ios.json and android.json, also platforms/ios/ios.json and platforms/android/android.json to make sure it works
